version: '3.5'
services:
  ddns-r53:
    container_name: ddns-r53
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./config.env
    network_mode: host
    restart: always
