env:
  APP: 'ddns-r53'

name: 'Workflow'
on: push

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:

# Checkout Repo
      - name: Checkout - Repository
        uses: actions/checkout@master

# Docker - Login
      - name: Docker - Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

# Install - QEMU
      - name: Install - QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

#  Install - Buildx
      - name: Install - Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

# Docker - Build & Push
      - name: Docker - Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.cache-${{ env.APP }}
          key: ${{ runner.os }}-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Docker - Build/Push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v6,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.APP }}:latest
          cache-from: type=local,src=/tmp/.cache-${{ env.APP }}
          cache-to: type=local,dest=/tmp/.cache-${{ env.APP }}
