env:
  DOCKER_IMAGE: 'ddns-r53'

name: 'Workflow'
on: push

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:

# Checkout Repo
      - name: Checkout - Repository
        uses: actions/checkout@master

# Docker Hub Login
      - name: Docker - Hub - Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

# Install - QEMU
      - name: Docker - QEMU - Install
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

#  Install - Buildx
      - name: Docker - Buildx - Install
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

# Cache
      - name: Docker - Buildx - Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

# Docker Image - Build & Push
      - name: Docker - Image - Push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7
          # platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
