env:
  DOCKER_IMAGE: 'ddns-r53'

name: 'Workflow'
on: push

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:

# Checkout Repo
      - name: 'Checkout - Repository'
        uses: actions/checkout@master

# Buildx - Install
      - name: Docker - Buildx - Install
        uses: docker/setup-buildx-action@v1

# Docker Hub Login
      - name: Docker - Hub - Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

# Docker Image - Tag, Build, & Push
      - name: Docker - Image - Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
